vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /build/images/user_pictures/profile/
            upload_destination: '%kernel.project_dir%/assets/images/user_pictures/profile/'
            namer: vich_uploader.namer_origname

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true